### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by qwantanius** [sipcapture/hepgen.js#11]
1. No input validating
2. No answers for any case
3. Good to see -h or --help options
![image](https://user-images.githubusercontent.com/62115635/108638398-1b819a80-74a0-11eb-8e79-9637f254b919.png)
For example:
-----case 1:
input> ```node hepgen.js -s 127.0.1 -p 9060 -c ./config/b2bcall.js```
output> ```common output of hepgen with logs```
-----case 2:
input>```node hepgen.js -s 127.0.0.1 -p 9060 -c ./config/b2bcall.js```
output> ```error of -s key --> '127.0.0.1' ```
-----case 3:
input>```node hepgen.js -s 127.0.0.1 -c ./config/b2bcall.js```
output> ```error of input -> missing -p 'port' option ```
e.t.c

**Comment by adubovikov** [comment]
sorry, can you please be more specific, what is a question ?

**Comment by lmangani** [comment]
I'm afraid HEPgen is not designed for this type of usage but rather for scripting purposes and CI/Validation/Development. 
I can although confirm it defaults to 127.0.0.1:9060 unless there are -s/-p options so it won't fail unless the scenario does not exist or is malformed. If you have a more specific question or proposal feel free to extend.

Thanks!
